version: '3'

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: demo-app
    container_name: demo-container
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  postgres-data: